include: package:lints/recommended.yaml

linter:
  rules:
    camel_case_extensions: true
    camel_case_types: true
    constant_identifier_names: true
    curly_braces_in_flow_control_structures: true
    directives_ordering: true
    file_names: true
    library_prefixes: true
    lines_longer_than_80_chars: false
    non_constant_identifier_names: true
    package_names: true

formatter:
  page_width: 120